# Build the chickendipR package.  This will produce a file called
# `chickendipR.x.y.z.tar.gz` You can give the .tar.gz file to all your fiends so
# they can use the freshest version of the chickendipR package... "like a boss".
build:
	R CMD build .

# Build Documentation
	R -e 'roxygen2::roxygenize()'
# Build and install the chickendipR package. For more on how this will affect
# your environment see the INSTALL help docs by running, from the command line:
#
#     > R CMD INSTALL --help
install:
	R CMD INSTALL --build .

# Build the documentation for the package.  Once the build is complete, your
# system will try to open the file.  The PDF view is the is specified with the
# environment variable `R_PDFVIEWER`
doc:
	R CMD Rd2pdf -o chickendipR.pdf .

# Run the test suite
test:
	R -e 'devtools::test()'

# Often one wants to check that the package is valid for cran submission
# if you run
#
# 	  > make build
#
# a .tar.gz file will be built.  Assume that the file is called
# `chickendipR_x.y.z.tar.gz`  We can check the file by running
#
# 	  > make TGZ=chickendipR_x.y.z.tar.gz check
check:
	R CMD check --as-cran $(TGZ)

.PHONY: veryclean clean

# clean up the "important" files generated by other targets
veryclean: clean
	rm -f src/chickendipR.so
	rm -f chickendipR_*.tar.gz
	rm -f chickendipR.pdf
	rm -rf chickendipR.Rcheck

# clean up the "unimportant" files generated by other targets
clean:
	find . -name '*.o' -exec rm {} \;
	rm -f src/RcppExports.cpp R/RcppExports.R
